### ISSUE TITLE
dataTable not rendering

### ISSUE THREAD

**Issue by stoltzmaniac** [stoltzmaniac/Medicare#10]
the dataTable used to render (third tab) and now it is not. It appears as if the data is still there because it is working properly elsewhere - cannot figure it out.

**Comment by ginberg** [comment]
@stoltzmaniac for me the datatable is still rendering..
![datatable](https://cloud.githubusercontent.com/assets/7089667/26765136/e05f72fa-4975-11e7-852b-43c83404896f.png)
any error messages?

**Comment by stoltzmaniac** [comment]
@ginberg are you pulling the most recent version? I don't have it running on shinyapps.io due to the issues. Perhaps It's just my RStudio, I'all double check later tonight.

**Comment by ginberg** [comment]
yes I have updated from your github code (I see the different colors in the plot on the first tab)

**Comment by stoltzmaniac** [comment]
Oh yeah... makes sense :) .  I just published the latest version and it has the problems, let me know what you think https://stoltzmaniac.shinyapps.io/medicare_data/

**Comment by stoltzmaniac** [comment]
![image](https://cloud.githubusercontent.com/assets/23501850/26786009/406589ea-49c2-11e7-9c2b-06b52e112694.png)

**Comment by stoltzmaniac** [comment]
![image](https://cloud.githubusercontent.com/assets/23501850/26786043/684f8d66-49c2-11e7-969c-c9de05089ca1.png)

**Comment by stoltzmaniac** [comment]
RStudio issue - not fully certain which package caused this but it resolved.
