### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by ginberg** [stoltzmaniac/Medicare#2]
Hi Scott,

I also read your blog post. Since I am interested in health care, I would like to contribute:)

I already made some changes, see attachment.
My question is about the plot. Did you have a specific reason to plot measure vs score filled by hospital. I changed it to plot hospital vs score (for given measure) since I think it is easier to read. Also, when you fill by hospital, it's hard to sort on Score. What do you think about it?

best,Ger
![medicare](https://cloud.githubusercontent.com/assets/7089667/26101542/b74a1650-3a5b-11e7-8ac8-192665b4f57c.png)

**Comment by stoltzmaniac** [comment]
Love it! Thanks for the contribution! can you submit a pull request? I'm more than happy to add it. The reason I had a bad chart in there was simply because I didn't take the time - i will have a lot more time in early June to start making fun additions

**Comment by ginberg** [comment]
Okay, I understand. I submitted the pull request and will look if I can create some other interesting plots..
