### ISSUE TITLE
leaflet

### ISSUE THREAD

**Issue by ginberg** [stoltzmaniac/Medicare#5]
Hi Scott,

I added a tab to display hospitals on a map. Radius of circles is related to the square root of the relative score. Just a starting point, it should be improved. Let me know if you have some ideas or improvements about it okay?

best,Ger

**Comment by stoltzmaniac** [comment]
Thank you! I like the idea of it for sure. I am having trouble getting the connection to work properly online, but I will get it all uploaded soon.
