### ISSUE TITLE
No Dynamic Filtering

### ISSUE THREAD

**Issue by stoltzmaniac** [stoltzmaniac/Medicare#8]
The filters on the left for "infection" and "metric" work but do not work with each other. 

The same problem exists with City and State (cities should only show up which are within the state).
@ginberg - any ideas?
@chipoglesby - any ideas on this? I think you solved this on something else if I'm not mistaken...

**Comment by ginberg** [comment]
@stoltzmaniac you can use https://shiny.rstudio.com/reference/shiny/latest/updateSelectInput.html
I just created a pull request so you can see how to use it
Maybe the updating should be extended, for example when selecting a state or city, should the infection dropdown be updated?

**Comment by stoltzmaniac** [comment]
Ahhhhh, that's a great piece of built-in functionality. I was trying to build that out myself and couldn't get it to work - makes way more sense that it's already there... thanks. I guess all menus could filter off of each other in a certain sense, I'll look into it more. Finally got back from 2+ weeks on the road tonight so I'm finally able to read through everything.

**Comment by ginberg** [comment]
Okay:-) Yeah, I think we still should add some more dynamic behaviour. Since for certain infections the bar plot is not drawn when selecting a city/state (which means there is no data)
